### ISSUE TITLE
Restructure the wiki to be able to render subsections

### ISSUE THREAD

**Issue by joomakelastudent** [softgitron/potku-console#10]
Remodel the Wiki's visual structure to allow subsections to be displayed inside the navigation sidebar.

As a developer I can use dedicated wiki subsections to link related data together, so that searching the documentation of related articles is vastly improved.

For example, with subsections, different parts of the IPC library can all be located under one section without flooding the wiki's homepage or navigation bar.

**Comment by softgitron** [comment]
This is now fixed by adding custom sidebar in the _Sidebar.md. For now this file must be updated manually, but in the future there could be a pipeline job that does the updating automatically. For example [this project](https://github.com/adriantanasa/github-wiki-sidebar/wiki/Installation) can be used for automatic sidebar generation.
